name: CoinAPIcore
main: Ki\CoinAPIScore\Main
api: 4.0.0
version: 1.0.0
author: Ki
web: https://web.the-void.fun/   GitHub: https://github.com/Anditem0
description: Hiện coin Lên bản thông tin
depend: [ScoreHud, CoinAPI]
